name: 'Flexlate After-Merge Action'
description: 'Official Flexlate Github Action to be run after merges. Merges Flexlate feature branches into main branches and handles merge conflict resolution flow.'
runs:
  using: composite
  steps:
    - run: echo hello world
      shell: bash
  